Commenting out run_downloaded_pipeline for now

diff --git a/.github/workflows/download_pipeline.yml b/.github/workflows/download_pipeline.yml
--- a/.github/workflows/download_pipeline.yml
+++ b/.github/workflows/download_pipeline.yml
@@ -97,38 +97,38 @@ jobs:
           echo "Initial container image count: $image_count"
           echo "IMAGE_COUNT_INITIAL=$image_count" >> "$GITHUB_OUTPUT"
 
-      - name: Run the downloaded pipeline (stub)
-        id: stub_run_pipeline
-        continue-on-error: true
-        env:
-          NXF_SINGULARITY_CACHEDIR: ./singularity_container_images
-          NXF_SINGULARITY_HOME_MOUNT: true
-        run: nextflow run ./${{needs.configure.outputs.REPOTITLE_LOWERCASE }}/$( sed 's/\W/_/g' <<< ${{ needs.configure.outputs.REPO_BRANCH }}) -stub -profile test,singularity --outdir ./results
-      - name: Run the downloaded pipeline (stub run not supported)
-        id: run_pipeline
-        if: ${{ steps.stub_run_pipeline.outcome == 'failure' }}
-        env:
-          NXF_SINGULARITY_CACHEDIR: ./singularity_container_images
-          NXF_SINGULARITY_HOME_MOUNT: true
-        run: nextflow run ./${{ needs.configure.outputs.REPOTITLE_LOWERCASE }}/$( sed 's/\W/_/g' <<< ${{ needs.configure.outputs.REPO_BRANCH }}) -profile test,singularity --outdir ./results
+      # - name: Run the downloaded pipeline (stub)
+      #   id: stub_run_pipeline
+      #   continue-on-error: true
+      #   env:
+      #     NXF_SINGULARITY_CACHEDIR: ./singularity_container_images
+      #     NXF_SINGULARITY_HOME_MOUNT: true
+      #   run: nextflow run ./${{needs.configure.outputs.REPOTITLE_LOWERCASE }}/$( sed 's/\W/_/g' <<< ${{ needs.configure.outputs.REPO_BRANCH }}) -stub -profile test,singularity --outdir ./results
+      # - name: Run the downloaded pipeline (stub run not supported)
+      #   id: run_pipeline
+      #   if: ${{ steps.stub_run_pipeline.outcome == 'failure' }}
+      #   env:
+      #     NXF_SINGULARITY_CACHEDIR: ./singularity_container_images
+      #     NXF_SINGULARITY_HOME_MOUNT: true
+      #   run: nextflow run ./${{ needs.configure.outputs.REPOTITLE_LOWERCASE }}/$( sed 's/\W/_/g' <<< ${{ needs.configure.outputs.REPO_BRANCH }}) -profile test,singularity --outdir ./results
 
-      - name: Count the downloaded number of container images
-        id: count_afterwards
-        run: |
-          image_count=$(ls -1 ./singularity_container_images | wc -l | xargs)
-          echo "Post-pipeline run container image count: $image_count"
-          echo "IMAGE_COUNT_AFTER=$image_count" >> "$GITHUB_OUTPUT"
+      # - name: Count the downloaded number of container images
+      #   id: count_afterwards
+      #   run: |
+      #     image_count=$(ls -1 ./singularity_container_images | wc -l | xargs)
+      #     echo "Post-pipeline run container image count: $image_count"
+      #     echo "IMAGE_COUNT_AFTER=$image_count" >> "$GITHUB_OUTPUT"
 
-      - name: Compare container image counts
-        run: |
-          if [ "${{ steps.count_initial.outputs.IMAGE_COUNT_INITIAL }}" -ne "${{ steps.count_afterwards.outputs.IMAGE_COUNT_AFTER }}" ]; then
-            initial_count=${{ steps.count_initial.outputs.IMAGE_COUNT_INITIAL }}
-            final_count=${{ steps.count_afterwards.outputs.IMAGE_COUNT_AFTER }}
-            difference=$((final_count - initial_count))
-            echo "$difference additional container images were \n downloaded at runtime . The pipeline has no support for offline runs!"
-            tree ./singularity_container_images > ./container_afterwards
-            diff ./container_initial ./container_afterwards
-            exit 1
-          else
-            echo "The pipeline can be downloaded successfully!"
-          fi
+      # - name: Compare container image counts
+      #   run: |
+      #     if [ "${{ steps.count_initial.outputs.IMAGE_COUNT_INITIAL }}" -ne "${{ steps.count_afterwards.outputs.IMAGE_COUNT_AFTER }}" ]; then
+      #       initial_count=${{ steps.count_initial.outputs.IMAGE_COUNT_INITIAL }}
+      #       final_count=${{ steps.count_afterwards.outputs.IMAGE_COUNT_AFTER }}
+      #       difference=$((final_count - initial_count))
+      #       echo "$difference additional container images were \n downloaded at runtime . The pipeline has no support for offline runs!"
+      #       tree ./singularity_container_images > ./container_afterwards
+      #       diff ./container_initial ./container_afterwards
+      #       exit 1
+      #     else
+      #       echo "The pipeline can be downloaded successfully!"
+      #     fi
